import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'mi_proyecto.settings')  # Cambia 'mi_proyecto' por el nombre de tu proyecto
django.setup()

from django.contrib.auth.models import User
from mi_app.models import BandaPop, Comentario

bandas = [
    "ABBA", "Adele", "Ariana Grande", "Backstreet Boys", "Bananarama",
    "Beyoncé", "Billie Eilish", "Blackpink", "Britney Spears", "Bruno Mars",
    "Camila Cabello", "Carly Rae Jepsen", "Coldplay", "Dua Lipa", "Ed Sheeran",
    "Ellie Goulding", "Enrique Iglesias", "Fifth Harmony", "Florence + The Machine", "George Michael",
    "Gwen Stefani", "Harry Styles", "Halsey", "Imagine Dragons", "INXS",
    "James Blunt", "Janet Jackson", "Jason Mraz", "Jennifer Lopez", "Jessie J",
    "Jonas Brothers", "Justin Bieber", "Katy Perry", "Kelly Clarkson", "Kylie Minogue",
    "Lady Gaga", "Lana Del Rey", "Little Mix", "Lorde", "Luis Fonsi",
    "Madonna", "Mariah Carey", "Maroon 5", "Miley Cyrus", "Niall Horan",
    "NSYNC", "Olivia Rodrigo", "One Direction", "OneRepublic", "P!nk",
    "Paramore", "Pharrell Williams", "Post Malone", "Rihanna", "Robbie Williams",
    "Rosalía", "Sabrina Carpenter", "Sam Smith", "Selena Gomez", "Shakira",
    "Shawn Mendes", "Sia", "Spice Girls", "Sugababes", "Take That",
    "Taylor Swift", "The Chainsmokers", "The Weeknd", "Tove Lo", "Troye Sivan",
    "Twice", "U2", "Usher", "Vance Joy", "Vanessa Carlton",
    "Walk The Moon", "Whitney Houston", "Zara Larsson", "Zayn Malik", "BTS",
    "EXO", "Red Velvet", "TXT", "Super Junior", "Monsta X",
    "CNCO", "Morat", "Reik", "Ha*Ash", "Jesse & Joy",
    "Axel", "Lali", "Tini", "Karol G", "RBD",
    "Camilo", "Danny Ocean", "Sebastián Yatra", "Danna Paola", "Aitana"
]

# Si hay menos de 100 bandas, genera nombres ficticios adicionales
while len(bandas) < 100:
    bandas.append(f"Banda Ficticia {len(bandas)+1}")

descripciones = [
    "Grupo sueco pionero del pop internacional y ganador de Eurovisión.",
    "Cantante británica reconocida por su poderosa voz y letras emotivas.",
    "Artista pop estadounidense con múltiples éxitos globales.",
    "Boy band icónica de los años 90 con millones de discos vendidos.",
    "Dúo femenino británico famoso por su estilo y energía.",
    "Superestrella mundial, ex integrante de Destiny's Child.",
    "Cantautora joven con un estilo único y letras profundas.",
    "Grupo femenino surcoreano líder en el K-pop internacional.",
    "Princesa del pop con una carrera llena de éxitos.",
    "Cantante y productor estadounidense con gran carisma en el escenario.",
    "Cantante cubano-estadounidense con gran proyección internacional.",
    "Artista canadiense conocida por su hit 'Call Me Maybe'.",
    "Banda británica con himnos pop y shows espectaculares.",
    "Cantante británica con estilo moderno y gran presencia escénica.",
    "Cantautor británico con récords de ventas y premios.",
    "Cantautora británica con voz etérea y éxitos pop.",
    "Cantante español con una carrera internacional destacada.",
    "Grupo femenino estadounidense con gran influencia en el pop.",
    "Banda británica de indie pop con gran reconocimiento.",
    "Cantante británico con una carrera legendaria en el pop.",
    "Cantante y compositora estadounidense con estilo propio.",
    "Ex integrante de One Direction y exitoso solista británico.",
    "Cantante estadounidense con letras introspectivas y gran voz.",
    "Banda estadounidense de pop rock con éxitos mundiales.",
    "Banda australiana influyente en la música pop y rock.",
    "Cantautor británico conocido por baladas emotivas.",
    "Cantante estadounidense con una carrera llena de éxitos.",
    "Cantautor estadounidense con estilo relajado y positivo.",
    "Cantante y actriz estadounidense con gran trayectoria.",
    "Cantante británica con potente voz y presencia escénica.",
    "Trío estadounidense con gran éxito entre el público juvenil.",
    "Cantante canadiense con una carrera meteórica en el pop.",
    "Cantante estadounidense con éxitos globales y estilo propio.",
    "Cantante estadounidense ganadora de American Idol.",
    "Cantante australiana con una carrera internacional.",
    "Artista estadounidense con gran impacto en la cultura pop.",
    "Cantautora estadounidense con estilo alternativo y letras profundas.",
    "Grupo femenino británico con gran éxito en el pop.",
    "Cantautora neozelandesa con estilo alternativo y letras poéticas.",
    "Cantante puertorriqueño con éxitos internacionales.",
    "Reina del pop con una carrera legendaria y revolucionaria.",
    "Cantante estadounidense con voz potente y baladas icónicas.",
    "Banda estadounidense con múltiples éxitos en las listas.",
    "Cantante estadounidense con gran versatilidad y carisma.",
    "Cantante irlandés ex integrante de One Direction.",
    "Boy band estadounidense famosa en los 90 y 2000.",
    "Cantante y actriz estadounidense revelación de la nueva generación.",
    "Banda británica de pop juvenil con gran éxito internacional.",
    "Banda estadounidense de pop rock con éxitos radiales.",
    "Cantante estadounidense con estilo único y gran energía.",
    "Banda estadounidense de pop punk con gran base de fans.",
    "Cantante y productor estadounidense con éxitos globales.",
    "Cantante estadounidense con estilo innovador y gran éxito.",
    "Cantante barbadense con múltiples premios y éxitos.",
    "Cantante británico con gran carisma y trayectoria.",
    "Cantante española con proyección internacional y estilo propio.",
    "Cantante estadounidense con gran talento y versatilidad.",
    "Cantante británico con voz inconfundible y éxitos pop.",
    "Cantante y actriz estadounidense con gran popularidad.",
    "Cantante colombiana reconocida mundialmente por su talento.",
    "Cantante canadiense con gran proyección internacional.",
    "Cantautora australiana con voz única y estilo propio.",
    "Grupo femenino británico icónico de los años 90.",
    "Grupo femenino británico con gran éxito en el pop.",
    "Banda británica de pop con gran trayectoria.",
    "Cantautora estadounidense con récords de ventas y premios.",
    "Dúo estadounidense de música electrónica y pop.",
    "Cantante canadiense con estilo innovador y éxitos globales.",
    "Cantautora sueca con gran proyección internacional.",
    "Cantante australiano con estilo fresco y juvenil.",
    "Grupo femenino surcoreano con gran éxito internacional.",
    "Banda irlandesa legendaria con décadas de éxitos.",
    "Cantante estadounidense con gran talento y presencia.",
    "Cantante australiano con estilo indie y letras emotivas.",
    "Cantautora estadounidense con gran talento y popularidad.",
    "Banda estadounidense de indie pop con gran energía.",
    "Cantante estadounidense con voz poderosa y legado musical.",
    "Cantante sueca con gran proyección internacional.",
    "Cantante británico ex integrante de One Direction.",
    "Banda surcoreana de K-pop con éxito mundial.",
    "Banda surcoreana de K-pop con gran base de fans.",
    "Grupo femenino surcoreano con estilo innovador.",
    "Banda surcoreana de K-pop con gran trayectoria.",
    "Banda surcoreana de K-pop con gran energía.",
    "Boy band latina con gran éxito internacional.",
    "Banda colombiana de pop latino con letras emotivas.",
    "Banda mexicana de pop romántico con gran popularidad.",
    "Dúo mexicano de pop con gran trayectoria.",
    "Dúo mexicano de pop con letras emotivas.",
    "Cantautor argentino con gran proyección internacional.",
    "Cantante argentina con estilo pop moderno.",
    "Cantante argentina con gran popularidad juvenil.",
    "Cantante colombiana con éxitos internacionales.",
    "Banda mexicana de pop juvenil con gran éxito.",
    "Cantautor colombiano con estilo fresco y popular.",
    "Cantante venezolano con éxitos en el pop latino.",
    "Cantante colombiano con gran proyección internacional.",
    "Cantante y actriz mexicana con gran talento.",
    "Cantante española con gran proyección internacional."
]

# Si hay menos descripciones que bandas, rellena con descripciones genéricas
while len(descripciones) < len(bandas):
    descripciones.append(f"Banda de pop internacional con gran proyección. {bandas[len(descripciones)]} es reconocida por su estilo único.")

for nombre, descripcion in zip(bandas, descripciones):
    BandaPop.objects.get_or_create(nombre=nombre, defaults={'descripcion': descripcion})

print("¡Bandas con descripciones cargadas exitosamente!")

comentarios = [
    "¡Una banda increíble!",
    "Su música me acompaña todos los días.",
    "Tienen un estilo único.",
    "Siempre innovando en el pop.",
    "Sus conciertos son inolvidables.",
    "Me encanta su último álbum.",
    "Son leyenda del pop.",
    "Sus letras me inspiran.",
    "¡Espero verlos en vivo algún día!",
    "Son parte de mi playlist favorita.",
    "Tienen una energía inigualable.",
    "Cada canción es un éxito.",
    "Su historia es fascinante.",
    "Han marcado generaciones.",
    "Siempre sorprendiendo a sus fans.",
    "Me identifico con sus canciones.",
    "Su evolución musical es admirable.",
    "Son referentes en la industria.",
    "¡No puedo dejar de escucharlos!",
    "Su voz es espectacular.",
    "Tienen colaboraciones geniales.",
    "Su imagen es icónica.",
    "Han ganado muchos premios.",
    "Su creatividad no tiene límites.",
    "Me hacen bailar siempre.",
    "Son inspiración para muchos.",
    "Su talento es indiscutible.",
    "Han roto muchos récords.",
    "Su presencia en el escenario es única.",
    "Me emocionan sus baladas.",
    "Son parte de mi infancia.",
    "Siempre están en tendencia.",
    "Su música une a las personas.",
    "Han dejado huella en el pop.",
    "Su estilo es inconfundible.",
    "Me alegra escucharlos.",
    "Son un fenómeno global.",
    "Sus videoclips son geniales.",
    "Siempre espero sus lanzamientos.",
    "Son muy versátiles.",
    "Me gusta su actitud positiva.",
    "Han hecho historia.",
    "Su discografía es impresionante.",
    "Son un ejemplo de perseverancia.",
    "Me motivan a seguir mis sueños.",
    "Su música trasciende fronteras.",
    "Son muy carismáticos.",
    "Me encanta su look.",
    "Siempre logran sorprenderme.",
    "Son muy originales.",
    "Su sonido es fresco.",
    "Han colaborado con grandes artistas.",
    "Me gusta su mensaje.",
    "Son muy auténticos.",
    "Su música me relaja.",
    "Siempre están reinventándose.",
    "Son muy profesionales.",
    "Me gusta su sencillez.",
    "Son muy cercanos a sus fans.",
    "Su música es atemporal.",
    "Me hacen sentir feliz.",
    "Son muy creativos.",
    "Siempre están presentes en las listas.",
    "Me gusta su pasión.",
    "Son muy trabajadores.",
    "Su música es un viaje.",
    "Me encanta su energía.",
    "Son muy talentosos.",
    "Siempre están innovando.",
    "Me gusta su humildad.",
    "Son muy influyentes.",
    "Su música es poderosa.",
    "Me gusta su ritmo.",
    "Son muy populares.",
    "Su música es pegadiza.",
    "Me gusta su diversidad.",
    "Son muy dedicados.",
    "Su música es emocionante.",
    "Me gusta su autenticidad.",
    "Son muy respetados.",
    "Su música es inspiradora.",
    "Me gusta su evolución.",
    "Son muy admirados.",
    "Su música es mágica.",
    "Me gusta su trayectoria.",
    "Son muy queridos.",
    "Su música es inolvidable.",
    "Me gusta su profesionalismo.",
    "Son muy exitosos.",
    "Su música es vibrante.",
    "Me gusta su simpatía.",
    "Son muy originales.",
    "Su música es única.",
    "Me gusta su entrega.",
    "Son muy apasionados.",
    "Su música es genial.",
    "Me gusta su frescura.",
    "Son muy innovadores.",
    "Su música es divertida.",
    "Me gusta su conexión con el público.",
    "Son muy carismáticos.",
    "Su música es fantástica."
]

# Si hay menos de 100 comentarios, rellena con comentarios genéricos
while len(comentarios) < len(bandas):
    comentarios.append("¡Gran banda de pop!")

usuario = User.objects.first()
if not usuario:
    usuario = User.objects.create_user(username='usuario_demo', password='demo1234')

for nombre, comentario in zip(bandas, comentarios):
    banda = BandaPop.objects.filter(nombre=nombre).first()
    if banda:
        Comentario.objects.create(banda=banda, usuario=usuario, texto=comentario)

print("¡100 comentarios, uno por banda, cargados exitosamente!")
