# Generated by Django 5.2 on 2025-05-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_bandapop_descripcion_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandapop',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='bandas/'),
        ),
    ]
